
####################################
##### Throw-TNT by Xerro_Patau #####
####################################

Left-Click-Throw: true
Right-Click-Throw: false
Throw-Power: 1
Fuse-Ticks: 80 # minecraft default is 80

Action-Bar-Warning:
  Enable: true
  Text: "&cTNT is activated by pressing Left Mouse Button!"